title: Consejos de aprendiz perpetuo
baseurl: "/rlstevenson" # the subpath of your site, e.g. /blog
collections:
  authors:
    output: true

defaults:
  - scope:
      path: "/rlstevenson"
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "/rlstevenson"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/rlstevenson"
    values:
      layout: "default"
