title: Consejos de aprendiz perpetuo
collections:
  authors:
    output: true

domain: rodrom.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://rodrom.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /rlstevenson/      # place folder name if the site is served in a subfolder

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
